Famono.scope('famous-polyfills/index', [], function(require, define, exports, module) {
// This file was auto generated by Famono
define(function(require, exports, module) { module.exports = famous.polyfills; });
});