module.exports = function () {
  console.log(
    "StarryNight... managing your application life-cycle from installation to testing to deployment."
  );
  console.log( "Usage:" );
  console.log( "  display-env" );
  console.log( "  audit-permissions" );
  // console.log( "  audit --fda --hipaa --permissions" );
  console.log( "  run-tests --framework <frameworkName> --autogenerated" );
  console.log( "  scaffold --boilerplate <boilerplateName> --framework <frameworkName>" );
  console.log( "  pattern --url http://github.com/account/repo" );
  console.log( "  rename --from <originalTerm> --to <newTerm> -root <directoryRoot>" );
  console.log( "  find-and-replace --from <originalTerm> --to <newTerm> -root <directoryRoot>" );
  console.log( "  refactor --from <originalTerm> --to <newTerm> -root <directoryRoot>" );
  console.log( "  create --package foo:mypackage --from /path/to/component" );
  console.log( "  extract-ids /path/to/<filename>" );
  console.log( "  extract-classes /path/to/<filename>" );
  console.log( "  extract-tests-for /path/to/<filename>" );
  console.log( "  generate --default --travis --circle --linters --autoconfig --release");
  console.log( "  generate-release-json" );
  console.log( "  generate-autoconfig" );
  console.log( "  generate-ci <ciProviderName>" );
  console.log( "  generate-linters" );
  console.log( "  fetch" );
  console.log( "  compact" );
  // console.log( "  validate --app --packages --all" );
  // console.log( "  verify --app --packages --all" );
};
