# this travis.yml file is for the leaderboard-nightwatch example, when run standalone
language: node_js

node_js:
  - "0.10.38"

services:
  - mongodb

sudo: required

env:


cache:
  directories:
    - .meteor/local/build/programs/server/assets/packages
    - .meteor

before_install:
  # set up the node_modules dir, so we know where it is
  - "mkdir -p node_modules &"

  # install starrynight, so we can launch nightwatch and selenium
  # - "npm install -g nightwatch"

  # install starrynight, so we can launch nightwatch and selenium
  - "npm install -g starrynight"

  # npm install -g selenium-server-standalone-jar"

  #- "which node"
  #- "which starrynight"

  - "export CONFIG_PREFIX=`npm config get prefix`"
  #- "echo $CONFIG_PREFIX"

  - "export TRAVIS=true"


  # fire up xvfb on port :99.0
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

  # set the xvfb screen size to 1280x1024x16
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

  # install meteor
  - "curl https://install.meteor.com | /bin/sh"

  # give meteor a few seconds after installing
  - "sleep 10"

  # setup Meteor app
  - "cd webapp"
  - "meteor &"

  # give Meteor some time to download packages, init data, and to start
  - "sleep 60"

#install:
#  - npm install

# we're not installing starrynight globally, so we run the script from the local node_modules folder
script: "starrynight -run-tests acceptance"
